version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: flas-db
    environment:
      POSTGRES_USER: flas
      POSTGRES_PASSWORD: flas1234
      POSTGRES_DB: flas
    ports:
      - '5432:5432'
    volumes:
      - flas-pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  flas-pgdata:
